sudo: required

language: cpp

compiler:
  - clang
os:
  - linux

addons:
  apt:
    sources:
      - kalakris-cmake
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang-3.8
      - gfortran
env: CXX_COMPILER='clang++-3.8' C_COMPILER='clang-3.8' Fortran_COMPILER='gfortran'

cache:
  directories:
    - mpich
    - mpich-3.2

before_install:
  - export CC=${C_COMPILER}
  - export CXX=${CXX_COMPILER}
  - export FC=${Fortran_COMPILER}
  - ./install-mpich.sh
  - export MPI_HOME=$(pwd)/mpich
  - export MPI_DIR=$(pwd)/mpich
  - export MPI_PATH=$(pwd)/mpich

install:
  - echo $CC
  - echo $CXX
  - echo $FC
  - $FC --version
  - $CC --version
  - $CXX --version
  - pushd . && cd $HOME
  - git clone -b master https://github.com/ecmwf/ecbuild
  - git clone -b master https://github.com/ecmwf/eckit
  - git clone -b master https://github.com/ecmwf/fckit
  - export PATH=$HOME/ecbuild/bin:$PATH
  - mkdir -p $HOME/builds/eckit && cd $HOME/builds/eckit
  - ecbuild --build=debug --prefix=$HOME/deps -- $HOME/eckit
  - make -j8 install
  - mkdir -p $HOME/builds/fckit && cd $HOME/builds/fckit
  - ecbuild --build=debug --prefix=$HOME/deps -- $HOME/fckit
  - make -j8 install
  - popd

script:
  - echo $CC
  - echo $CXX
  - echo $FC
  - $FC --version
  - $CC --version
  - $CXX --version
  - $CXX main.cc -o main
  - ./main
  - git clone -b master https://github.com/ecmwf/atlas
  - mkdir build && cd build
  - ecbuild --build=debug --prefix=$HOME/deps ../atlas
  - make -j8
  - ctest
  
