sudo: false

language: cpp


# Workaround for https://github.com/travis-ci/travis-ci/issues/4681
matrix:
  - TRAVIS_EMPTY_JOB_WORKAROUND=true


cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/openmpi
    - ${TRAVIS_BUILD_DIR}/deps/mpich
    - ${TRAVIS_BUILD_DIR}/deps/eckit
    - ${TRAVIS_BUILD_DIR}/deps/fckit


matrix:
  exclude:

    - env: TRAVIS_EMPTY_JOB_WORKAROUND

  include:

    # - os: linux
    #   compiler: clang
    #   env: 
    #     - CACHE_NAME=linux-clang38-mpich
    #     - CXX_COMPILER='clang++-3.8' C_COMPILER='clang-3.8' Fortran_COMPILER='gfortran'
    #     - MPI='mpich'
    #   addons: &clang38
    #     apt:
    #       sources:  ['llvm-toolchain-precise', 'ubuntu-toolchain-r-test']
    #       packages: ['clang-3.8', 'gfortran']

    - os: linux
      compiler: clang
      env:
        - CACHE_NAME=linux-clang38-openmpi
        - CXX_COMPILER='clang++-3.8' C_COMPILER='clang-3.8' Fortran_COMPILER='gfortran'
        - MPI='openmpi'
      addons: *clang38

    # - os: linux
    #   compiler: gcc
    #   env: 
    #     - CACHE_NAME=linux-gcc5-mpich
    #     - CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran-5'
    #     - MPI='mpich' 
    #   addons: &gcc5
    #     apt:
    #       sources:  ['ubuntu-toolchain-r-test']
    #       packages: ['g++-5', 'gcc-5', 'gfortran-5']

    - os: linux
      compiler: gcc
      env:
        - CACHE_NAME=linux-gcc5-openmpi
        - CXX_COMPILER='g++-5' C_COMPILER='gcc-5' Fortran_COMPILER='gfortran-5'
        - MPI='openmpi'
      addons: *gcc5

    # - os: linux
    #   compiler: gcc
    #   env:
    #     - CACHE_NAME=linux-pgi-openmpi
    #     - CXX_COMPILER='pgc++' C_COMPILER='pgcc' Fortran_COMPILER='pgfortran'
    #     - MPI='openmpi'
    #     - PGI_VERSION="CommunityEdition"

    # - os: osx
    #   env: 
    #     - CACHE_NAME=osx-clang-mpich
    #     - CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran'
    #     - MPI=mpich
    #   osx_image: xcode9

    # - os: osx
    #   env: 
    #     - CACHE_NAME=osx-clang-openmpi
    #     - CXX_COMPILER='clang++' C_COMPILER='clang' Fortran_COMPILER='gfortran'
    #     - MPI=openmpi
    #   osx_image: xcode9

before_install:
  #################################################################
  # Fixes to pre-installed packages
  #################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew list oclint || brew cask uninstall oclint # Prevent conflict with gcc
    fi

  #################################################################
  # Set compilers
  #################################################################
  - |
    export CC=${C_COMPILER}
    export CXX=${CXX_COMPILER}
    export FC=${Fortran_COMPILER}

install:

  #################################################################
  # All dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  #################################################################
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  #################################################################
  # Install Compilers
  #################################################################
  - |
    ### Install gcc (homebrew)
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew upgrade gcc || brew install gcc
    fi
  - |
    ### Install PGI community edition
    if [[ "${PGI_VERSION:-notset}" == "CommunityEdition" ]]; then
      ${TRAVIS_BUILD_DIR}/install-pgi.sh --mpi
      PGI_INSTALL_DIR=${HOME}/pgi
      PGI_VERSION=$(basename "${PGI_INSTALL_DIR}"/linux86-64/*.*/)
      PGI_DIR=${PGI_INSTALL_DIR}/linux86-64/${PGI_VERSION}
      export PATH=${PGI_DIR}/bin:${PATH}
      export MPI_HOME=${PGI_DIR}/mpi/openmpi
      export PATH=${MPI_HOME}/bin:${PATH}
      CMAKE_OPTIONS="-DRT_LIB=/usr/lib/x86_64-linux-gnu/librt.so"
    fi


  #################################################################
  # Install CGAL
  #################################################################
  - |
    ### Install CGAL
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew upgrade cgal || brew install cgal
    fi

  #################################################################
  # Install MPI
  #################################################################
  - |
    ### Install MPI
    if [ -z ${MPI_HOME+x} ]; then
      travis_wait 25 ${TRAVIS_BUILD_DIR}/install-mpi.sh ${MPI}
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        export MPI_HOME=${DEPS_DIR}/${MPI}
        export PATH=${MPI_HOME}/bin:${PATH}
      fi
    fi

  #################################################################
  # Install CMake
  #################################################################
  - |
    ### Install CMake
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version

  #################################################################
  # Install ecbuild
  #################################################################
  - |
    ### Install ecbuild
    git clone -b master https://github.com/ecmwf/ecbuild ${DEPS_DIR}/ecbuild
    export PATH=${DEPS_DIR}/ecbuild/bin:${PATH}

  #################################################################
  # Install eckit
  #################################################################
  - |
    ### Install eckit
    export ECKIT_PATH=${DEPS_DIR}/eckit
    if [[ -z "$(ls -A ${ECKIT_PATH})" ]]; then
      ECKIT_SOURCE_DIR=${TRAVIS_BUILD_DIR}/downloads/eckit
      ECKIT_BUILD_DIR=${TRAVIS_BUILD_DIR}/builds/eckit
      git clone -b travis https://github.com/wdeconinck/eckit ${ECKIT_SOURCE_DIR}
      mkdir -p ${ECKIT_BUILD_DIR} && cd ${ECKIT_BUILD_DIR}
      ecbuild --build=debug --prefix=${ECKIT_PATH} -- ${CMAKE_OPTIONS} -DENABLE_TESTS=OFF ${ECKIT_SOURCE_DIR}
      make -j8 install
    fi

  #################################################################
  # Install fckit
  #################################################################
  - |
    ### Install fckit
    export FCKIT_PATH=${DEPS_DIR}/fckit
    if [[ -z "$(ls -A ${FCKIT_PATH})" ]]; then
      FCKIT_SOURCE_DIR=${TRAVIS_BUILD_DIR}/downloads/fckit
      FCKIT_BUILD_DIR=${TRAVIS_BUILD_DIR}/builds/fckit
      git clone -b master https://github.com/ecmwf/fckit ${FCKIT_SOURCE_DIR}
      mkdir -p ${FCKIT_BUILD_DIR} && cd ${FCKIT_BUILD_DIR}
      ecbuild --build=debug --prefix=${FCKIT_PATH} -- -DENABLE_TESTS=ON ${FCKIT_SOURCE_DIR}
      make -j8 install
    fi

  - cd ${TRAVIS_BUILD_DIR}

script:

  - |
    ATLAS_SOURCE_DIR=${TRAVIS_BUILD_DIR}/downloads/atlas
    ATLAS_BUILD_DIR=${TRAVIS_BUILD_DIR}/builds/atlas

  #################################################################
  # Download Atlas
  #################################################################
  - git clone -b master https://github.com/ecmwf/atlas ${ATLAS_SOURCE_DIR}

  #################################################################
  # Build Atlas
  #################################################################
  - mkdir -p ${ATLAS_BUILD_DIR} && cd ${ATLAS_BUILD_DIR}
  - ecbuild --build=debug -- ${CMAKE_OPTIONS} ${ATLAS_SOURCE_DIR}
  - make -j8
  - bin/atlas --info

  #################################################################
  # Test Atlas
  #################################################################
  - ctest

after_failure:

  - cd ${ATLAS_BUILD_DIR}
  - ctest -VV --rerun-failed
  - cat ecbuild.log
